Discord tickets: bug fixes + auto-changing ticket status
PacifistaMC/PacifistaBot pull request #9
Opened 2023-10-13 21:30 UTC by iGameCreep

Bug fixes around the code:
- Implemented the use of IDs in tickets topics to avoid searching members by name
- Auto changing ticket status: when created it is CREATED, when a moderator sends a message inside it is IN_PROGRESS, when closed it is CLOSED.
- Fixed API calls

2023-10-14 09:23 UTC, FunixG commented
Est-ce que tu peux mettre ta branche à jour avec master ? 🤍 y'a des conflits

2023-10-14 09:24 UTC, iGameCreep commented
Yes, je check ca

2023-10-14 10:20 UTC, iGameCreep commented
Ca devrait être bon et fonctionnel

2023-10-16 08:16 UTC, FunixG commented on core/pom.xml
> +    <build>
Pas besoin de rajouter de build pour le package core, vu qu'on ne fait pas de jar executable

2023-10-16 08:17 UTC, FunixG commented on discord-bot/pom.xml
>              <version>1.5.1.4</version>
il faudrait utiliser les variables pour les numéros de versions comme dans les autres projets exemple : ${fr.pacifista.plugins.version} c'est un exemple

2023-10-16 08:17 UTC, FunixG commented on discord-bot/pom.xml
> +            <version>2.0.0</version>
pareil ici

2023-10-16 08:19 UTC, FunixG requested changes
Petits changements à faire dans les pom.xml

2023-10-16 14:26 UTC, merged